#!/bin/bash --

cat lib/schema.json | \
    sed -e 's#"type": "object",#"type": "object", "unevaluatedProperties": false,#' \
    > lib/schema.strict.json
cat >lib/schemas.dart <<'EOF'
final loose = r'''
EOF
cat lib/schema.json >> lib/schemas.dart
cat >>lib/schemas.dart <<'EOF'
''';

final strict = r'''
EOF
cat lib/schema.strict.json >> lib/schemas.dart
cat >>lib/schemas.dart <<'EOF'
''';
EOF
