include: ../../../analysis_options.yaml

analyzer:
  enable-experiment:
    - macros
  exclude:
    # TODO: remove these when the analyzer supports macros enough to run them
    - bin/checks_main.dart
    - bin/injectable_main.dart
