name: macro_proposal
publish_to: none
environment:
  sdk: ">=2.12.0 <3.0.0"
dev_dependencies:
  dart_style: ^2.2.1
  _fe_analyzer_shared: any

# Override to the latest version of the in progress api.
dependency_overrides:
  _fe_analyzer_shared:
    git:
      url: https://github.com/dart-lang/sdk.git
      path: pkg/_fe_analyzer_shared
