#!/bin/bash --

set -e

# Analyze, format and test packages.
for package in dart_model dart_model_analyzer_service dart_model_repl \
    macro_client macro_host macro_protocol testing/scratch \
    testing/test_macro_annotations testing/test_macros; do
  pushd "$package"
  dart pub get

  # Skip analyzing packages that need augmentations to be generated.
  if ! grep -qr 'import augment' lib; then
    dart analyze --fatal-infos
  fi

  # Delete augmentation files.
  find . -name \*.a.dart | xargs --no-run-if-empty rm
  # Remove augmentation imports.
  sed -i -e 's#^import augment#// import augment#' $(find . -name \*.dart)
  # Format.
  dart format .
  # Put back augmentation imports.
  sed -i -e 's#^// import augment#import augment#' $(find . -name \*.dart)

  # Run tests if the test folder is present.
  if test -d test; then
    dart run test
  fi
  popd
done
