#!/bin/bash --

set -e

# Analyze, format and test packages.
for package in dart_model dart_model_analyzer_service dart_model_repl \
    macro_client macro_host macro_protocol testing/scratch \
    testing/test_macro_annotations testing/test_macros; do
  pushd "$package"
  dart pub get
  dart analyze --fatal-infos
  dart format .
  # Run tests if the test folder is present.
  if test -d test; then
    dart run test
  fi
  popd
done
