name: macro_client
publish-to: none

environment:
  sdk: ^3.4.0

dependencies:
  dart_model: any
  macro_protocol: any

dependency_overrides:
  dart_model:
    path: ../dart_model
  macro_protocol:
    path: ../macro_protocol
