#!/usr/bin/env -S bash --norc

apt-get update -qq
apt-get install -y --no-install-recommends \
    build-essential \
    texlive-latex-base \
    texlive-latex-extra \
    texlive-fonts-recommended \
    lmodern
cd specification
make
mkdir firebase
cp dartLangSpec.pdf firebase/DartLangSpecDraft.pdf
